import { SyncMode, Frequency } from '../types';

const mapSyncModeToDisposition = (mode: SyncMode): string => {
    switch(mode) {
        case 'full_load': return 'replace';
        case 'incremental_append': return 'append';
        case 'incremental_merge': return 'merge';
        default: return 'merge';
    }
};

const mapFrequencyToCron = (freq: Frequency): string => {
    switch(freq) {
        case 'hourly': return '0 * * * *';
        case 'daily': return '0 0 * * *';
        case 'weekly': return '0 0 * * 0';
        default: return 'None';
    }
};

export const generateDltPipeline = (name: string, source: string, destination: string, syncMode: SyncMode): string => {
  const safeName = name.toLowerCase().replace(/\s+/g, '_');
  const disposition = mapSyncModeToDisposition(syncMode);
  
  return `"""
Pipeline: ${name}
Sync Mode: ${syncMode}
Generated by ResidencyFlow Control Plane
"""

import dlt

def ${source}_source():
    """
    Connects to ${source}.
    """
    # This inherits automatically from dlt's verified source library
    # You would typically install: pip install dlt[${source}]
    pass

if __name__ == "__main__":
    # Configure the pipeline
    pipeline = dlt.pipeline(
        pipeline_name="${safeName}",
        destination="${destination}", 
        dataset_name="${safeName}_dataset",
        progress="log"
    )

    # In a real environment, you would call the actual source function
    # data = ${source}.load()

    # Run the pipeline
    load_info = pipeline.run(
        [{"id": 1, "name": "sample"}], # Replace with actual source iterator
        table_name="raw_data",
        write_disposition="${disposition}"${disposition === 'merge' ? ',\n        primary_key="id"' : ''}
    )

    print(load_info)
`;
};

export const generatePrefectFlow = (name: string, frequency: Frequency): string => {
  const safeName = name.toLowerCase().replace(/\s+/g, '_');
  const cron = mapFrequencyToCron(frequency);

  return `from prefect import flow, task
from pipelines.${safeName} import pipeline as dlt_pipeline

@task(retries=3)
def run_dlt_pipeline():
    """
    Executes the dlt pipeline.
    """
    return dlt_pipeline.run()

@flow(
    name="${name}"${cron !== 'None' ? `,\n    cron="${cron}"` : ''}
)
def ${safeName}_flow():
    """
    Orchestrates ${name}
    """
    result = run_dlt_pipeline()
    print(f"Pipeline finished with result: {result}")

if __name__ == "__main__":
    ${safeName}_flow()
`;
};